default:
  image: python:3.9-buster
  before_script:
    - apt-get update
    - pip install -r requirements.txt
pytest:
  stage: test
  script:
    - bash ./scripts/test.sh
  artifacts:
    when: always
    reports:
      junit: junitxml.xml