version=0.1
[default.global.parameters]
stack_name = "CTE-SDLC-StepFunctions"

[default.deploy.parameters]
s3_prefix = "CTE-SDLC-StepFunctions"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"